//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;

namespace Assets.Scripts.State
{
	public class ClientStateList : MonoBehaviour
	{
        public string playerName = "Player";
		//private IList<ClientState> Configs = new List<ClientState>();

		void Start()
        {

        }
	}
}

