//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Assets.Scripts.State;
using Assets.Scripts.Other;
using UnityEngine;

namespace Assets.Scripts.State
{
	public class ServerStateList : MonoBehaviour
    {
        public string playerName = "Server";
        public IDictionary<int, ServerState> serverConfigs = new Dictionary<int, ServerState>();
		public IDictionary<Tuple<string, int, int>, ClientState> clientConfigs = new Dictionary<Tuple<string, int, int>, ClientState>();

        void Start()
        {

        }
	}
}

