//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Assets.Scripts.State
{
    [Serializable]
    public class ServerState

	{
        public int CurrentYear;
        public int NumberOfClient;
        public string PlayerNameList;
        public int MaxVessels;
        public int MaintenanceFee;
        public int OilPrice;
        public long Recruitment;
        public int MarketValue;

        //private double[] marketValueByAge = new double[10];

		public ServerState()
		{

		}
	}
}

